FROM nginx:1.26-alpine

RUN apk add openssl && \
	mkdir -p /etc/ssl/private /etc/ssl/certs && \
	openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /etc/ssl/private/nginx.key \
	-out /etc/ssl/certs/nginx.crt \
	-subj "/C=KR/ST=Seoul/O=42Seoul"

EXPOSE 443

ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]
