apiVersion: 1

groups:
  - name: example
    folder: Example folder
    interval: 10s
    rules:
      - uid: high_system_load_alert
        title: High System Load
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: ${PROMETHEUS_UID}
            model:
              editorMode: code
              expr: scalar(node_load1{instance="node-exporter:9100",job="node-exporter"}) * 100 / count(count(node_cpu_seconds_total{instance="node-exporter:9100",job="node-exporter"}) by (cpu))
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              type: reduce
              reducer: last
          - refId: C
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                    - 75
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                    - B
                  reducer:
                    type: last
                  type: query
              expression: B
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          summary: "High system load detected"
        labels:
          severity: warning
