groups:
  - name: CPU_LOAD_ALERT
    rules:
      - alert: HighSystemLoad
        expr: |
          (
            scalar(node_load1{instance="node-exporter:9100",job="node-exporter"}) * 100 /
            count(count(node_cpu_seconds_total{instance="node-exporter:9100",job="node-exporter"}) by (cpu))
          ) > 75
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High system load detected"
